# Generated by Django 4.1.3 on 2022-11-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('todo', models.CharField(max_length=255, verbose_name='やること')),
                ('priority', models.IntegerField(choices=[(0, '小'), (1, '中'), (2, '大')], verbose_name='優先度')),
                ('complete_flag', models.BooleanField(default=False, verbose_name='完了フラグ')),
            ],
            options={
                'verbose_name': 'タスク',
                'verbose_name_plural': 'タスク',
                'db_table': 'task',
            },
        ),
    ]
